### ISSUE TITLE
are you kidding me?

### ISSUE THREAD

**Issue by davelet** [rockyzhengwu/nsfw#1]
上传了我儿子图片 结果竟然这样的

![image](https://user-images.githubusercontent.com/2161707/51583346-0b86dd80-1f0b-11e9-8e2d-ce985efe5b15.png)

**Comment by rockyzhengwu** [comment]
非常抱歉！ 谢谢您提供的 bad case 。

**Comment by xxllp** [comment]
随便试了几张，只要是女的照片很多都是badcase，感觉你这根本没训练好
